### PR TITLE
doc: describe palette and highlight semantics

### PR DESCRIPTION
**Pull request by antoineco**
> **Warning**
> Ongoing effort, open to early feedback.

### Description

Adds a dedicated documentation page for presenting the color palette and explaining the semantics of each color.

~The final document will also include a note about higher level design decisions, such as the usage (or not) of italics and the conscious differences between "classic" Vim and Treesitter highlights.~ (in a future PR)

### Screenshots

See live preview at https://github.com/antoineco/sainnhe-everforest/blob/palette/palette.md

### CODE REVIEW

**Comment by talwat** [comment]
I feel like now is the best time to implement something like this because of the palette change.

**Comment by antoineco** [comment]
@talwat I agree.

I just updated the doc with:
- New colors (https://github.com/sainnhe/everforest/compare/d855af5434...81041b4033)
- Hex color codes overlays

Can you please take a look and tell me what you think?

**Comment by talwat** [comment]
Sorry for the late response, I was doing a few things. 

I think it looks awesome.

**Comment by sainnhe** [comment]
Great job! It looks awesome 😎

I've updated the url in the wiki page.

**Pull request merged**
