### PR TITLE
Adjust background colors of light variants

### PR DESCRIPTION
**Pull request by sainnhe**
### Description

Similar to #108 but for light variants.

### CODE REVIEW

**Comment by sainnhe** [comment]
| Variant | Preview |
| :---: | :---: |
| Soft | soft |
| Medium | medium |
| Hard | hard |

**Comment by sainnhe** [comment]
@antoineco Hi, would you like to get it a try?

The three variants are more distinguishable now, and some background colors get more vibrant (this might be hard to notice).

**Comment by antoineco** [comment]
I think it might be hard for me to notice indeed, because I can't remember the last time I used a light color scheme I might not be able to assess the differences objectively :)

**Comment by sainnhe** [comment]
OK, IMO it should be fine now. I'm going to merge it.

**Pull request merged**
