### PR TITLE
Adjust background colors of medium/dark and hard/dark

### PR DESCRIPTION
**Pull request by sainnhe**
### Description

After using this color scheme for a period of time, I found some issues in the color palette.

1. Three background variants (soft, medium, hard) are not distinguishable enough. The initial idea is to learn from the design of gruvbox, but I was too conservative when I was designing the color palette, the distinction between these colors is not obvious.
2. The background colors don't look good on MacBook, the medium/dark background looks somewhat bright and the overall contrast is too low.

In this PR I'm trying to make the background colors of the medium/dark and hard/dark variants darker, and make them more distinguishable between each other.

I may try to adjust the light variants in a separate PR.

### CODE REVIEW

**Comment by sainnhe** [comment]
@antoineco Could you test the medium/dark variant on your machine?

**Comment by sainnhe** [comment]
| Variant | Preview |
| :---: | :---: |
| Soft | soft |
| Medium | medium |
| Hard | hard |

**Comment by antoineco** [comment]
I think that looks alright, slightly more contrast. I'm a Macbook user and I wasn't bothered by the original palette though.

Here is an animated comparison of the changes for the medium/dark variant:

ezgif-4-504c75e18a

**Comment by sainnhe** [comment]
IMG20221203180334

I think it's not the problem of true tone, the display difers.

Left is M1 MacBook Air and right is surface book 2, both use medium/dark variant.

**Comment by antoineco** [comment]
In the picture you shared the MacBook seems to actually have a _darker_ background to me, with a deeper contrast, whereas the Surface looks blue-ish.

Anyway, I don't have a strong opinion on this because every time I use a different display the colors are slightly different for any given program I use.

**Comment by sainnhe** [comment]
Actually I feel that surface book has higher contrast. This color scheme looks foggy in MacBook and I think a darker background might look better.

This color scheme is originally designed in surface book so everything looks OK on it, but when using it on MacBook I always feel that something goes wrong, so I think the palette may need to be adjusted.

Another reason is that I want the three variants more distinguishable, so I want the medium and hard variants to be darker.

**Comment by antoineco** [comment]
Works for me, I like the new background palette!

**Comment by talwat** [comment]
Wouldn't this require a lot of work to update all of the plugins for various applications? And if everforest is going through a palette change, maybe just making a separate color scheme entirely like everforest 2.0 would be a better idea considering it's technically going to be a different colorscheme.

**Comment by sainnhe** [comment]
> Wouldn't this require a lot of work to update all of the plugins for various applications?

Yeah, that's a problem, I'll email the plugin authors, hope they can follow the changes.

> And if everforest is going through a palette change, maybe just making a separate color scheme entirely like everforest 2.0 would be a better idea considering it's technically going to be a different colorscheme.

I'd like to consider this as an enhancement or a fix, which should happen on current color scheme. I don't think it's necessary to create a separate color scheme.

Btw, the changes are small, it's OK to continue to use the original palette.

**Comment by talwat** [comment]
While I do agree, I still think the change should only be made when all of the plugin authors have been able to update their plugins.

**Pull request merged**
