### PR TITLE
feat(ts): support Neovim 0.8 Treesitter hl groups

### LINKED ISSUE #89: Update Treesitter syntax highlight groups to be compatible with Neovim 0.8
As mentioned in the [last issue](https://this-week-in-neovim.org/2022/Aug/29) of the "This week in Neovim" newsletter, there were some recent radical changes to the Treesitter syntax highlight groups in Neovim which might affect color schemes.

Ref. https://github.com/neovim/neovim/commit/030b422d1e9517ed1b1c70fd8002b74881c80650 (part of https://github.com/neovim/neovim/pull/19931)

`TS` prefixed highlight groups are not used anymore (as of commit 92bc11a89 of neovim/neovim):

ts-new-groups

_edit: The hierarchy shown above is wrong because the Treesitter playground wasn't updated yet._

I'm not sure whether this is transitory, so I'm going to keep it open for a few days before suggesting actions, but this could be big for Everforest because it would mean ~both Treesitter and Vim highlights now need to follow the [same semantics](https://github.com/sainnhe/everforest/pull/81#issuecomment-1216751460) for colors and italics~.

---

**edit:** It looks like this is indeed the new behaviour. There is no more difference between the capture groups and the highlight groups. As a result, it is still possible to tell Treesitter syntax highlight groups apart from Vim ones because they are prefixed with `@`.

This table should explain the new behaviour in a nutshell:

|lang|nvim 0.7|nvim 0.8|
|-|-|-|
|any|`@variable` -> `TSVariable`|`@variable` -> `@variable`|
|foo|`@variable` -> `fooTSVariable` -> `TSVariable`|`@variable` -> `@variable.foo`|

Also, the fallback order is now implicitly `@foo.bar.lang` -> `@foo.bar` -> `@foo`

### PR DESCRIPTION
**Pull request by antoineco**
### Description

There is no more distinction between names of capture groups and names of highlight groups starting with neovim/neovim#19931.

Fixes #89

### Screenshots

_not applicable_

### CODE REVIEW

**Comment by antoineco** [comment]
After using this configuration for a few days, I'm now confident that linking Neovim 0.8 Treesitter capture groups to their "legacy" `TS`-prefixed counterpart is the simplest way to move on with the current Neovim development branch, while ensuring backward compatibility with older versions.

Merging

**Comment by rameshsanth** [comment]
i see below messages after picking up this change..
W18: Invalid character in group name
line  478:
W18: Invalid character in group name
line  479:
W18: Invalid character in group name
line  480:
W18: Invalid character in group name
line  481:
W18: Invalid character in group name
line  482:
W18: Invalid character in group name
line  483:
W18: Invalid character in group name
line  484:
W18: Invalid character in group name
line  485:
W18: Invalid character in group name
line  486:
W18: Invalid character in group name
line  487:
W18: Invalid character in group name
line  488:
W18: Invalid character in group name
line  489:
W18: Invalid character in group name
line  490:
W18: Invalid character in group name
line  491:
W18: Invalid character in group name
line  492:
W18: Invalid character in group name
line  493:
W18: Invalid character in group name
line  494:
W18: Invalid character in group name
line  495:
W18: Invalid character in group name
line  496:
W18: Invalid character in group name
line  497:
W18: Invalid character in group name
line  498:
W18: Invalid character in group name
line  499:
W18: Invalid character in group name

I'm running below version
NVIM v0.8.0-dev-914-gd4d27c41b
Build type: Release                                                                                                                                                                                                                            
LuaJIT 2.1.0-beta3
Compiled by foo@somehost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/foo/ocal/share/nvim"

**Comment by rameshsanth** [comment]
Issue no longer seen with newer nvim..

NVIM v0.8.0-dev-996-g090370263
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by antoineco** [comment]
@rameshsanth indeed, 0.8 is still in development and your version must be recent (less than 5 days from today) for these changes to be applicable.

**Pull request merged**
