### PR TITLE
Accessible colors for light palette

### PR DESCRIPTION
**Pull request by jssee**
### Description

The current light palette has several accent colors that do not pass accesibility standards. I've made a few slight
adjustments that in result lets the light color palette to acieve WCAG AA compliance, I didnt go any much further than
that since I feel it would change the essence of the colorscheme. This should make the light scheme a bit easier on the
eyes as well.

### Screenshots

before:
Screenshot 2024-01-31 at 1 58 26 PM

after:
image

### CODE REVIEW

**Comment by antoineco** [comment]
Definitely easier on the eyes in light mode 👍
The question now is whether we want to:
- create a separate `palette2` (fg, accents) for light mode
- add an accessibility option that can be switched on/off
- decide that this belongs in a fork, in case someone wants to maintain a variation of the original everforest

@sainnhe any thought on this? 🙂

**Comment by antoineco** [comment]
@jssee by the way, could you briefly explain the nature of the adjustments that you did? (e.g. shift the contrast of each color by n%, etc.)

**Comment by sainnhe** [comment]
This will indeed look better in a scene that requires high contrast. But IMO this should be maintained in a fork or a new project instead of in this one, because:

1. The color palette has been finalized, and should not be changed in the future.
2. The contrast ratio is deliberately designed to be low.

When designing everforest, I defined this color scheme as soft and vibrant. That’s said, I need to make some trade-offs in other aspects, e.g. the contrast.

For example, let’s take a look at the green colors before and after change. The contrast is indeed higher, but it’s not as vivid and vibrant as before. I choose between contrast and vibrancy, and adjust the color many times to achieve the effect I want.

As for creating a high contrast variant, to be honest I have already thought about this for at least 3 times, but each time I try to modify the color palette to have a higher contrast, I immediately realized that this is not what everforest should be like.

People may have some different ideas on the color designing. No problem! But I just want to say that I can’t satisfy everyone’s needs. I’ve designed another two light color schemes, namely edge and gruvbox material, both have a higher contrast than everforest, but even so, some people still think the contrast is not high enough.

Maybe you can maintain your own fork or start a new project instead.

**Comment by jssee** [comment]
@sainnhe your explanation is understandable! i didnt mean to force these changes into the project, i had been using them locally for a while and just figured others might benefit. 

I am a big fan of your work, i have used gruvbox-material for a long time and switched to my tweaked version of everforest recently and have been really enjoying it.

One suggestion for the future however is to design with aesthetics _and_ usability in mind. the context in which we use these themes is important, reading low contrast text for extended periods of time will cause extra strain on the reader and can cause permanent eye damage after a while. I know light themes in general are less popular than dark ones for coders, but still its important to consider all our users equally whenever possible.

Anyways, ill maintain my own fork as suggested, and thanks for considering these changes. I look forward to your future projects! 😃

**Pull request closed without merging**
