### PR TITLE
js: Clean up and adjust syntax highlights

### LINKED ISSUE #70: Strings and function names same color w/ polyglot in JS
### Operating system/version

Ubuntu 22.04 LTS

### Terminal emulator/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Tmux version

_No response_

### Feature matrix

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30)
Included patches: 1-3995
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       +tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-8W0Acv/vim-8.2.3995=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lm -ltinfo -lselinux -lsodium -lacl -lattr -lgpm -L/usr/lib -llua5.2 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.34/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -lpython3.10 -lcrypt -ldl -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-3.0 -lm -L/usr/lib
```

### Minimal vimrc that can reproduce this bug.

```
 " vim-plug
call plug#begin('~/.vim/plugged')
                  
Plug 'sheerun/vim-polyglot'
Plug 'sainnhe/everforest'
              
call plug#end()

" options
set background=dark
set termguicolors
colorscheme everforest
```

### Steps to reproduce this bug using minimal vimrc

1. Edit .js file using `vim test.js`
2. Insert a function and a string

### Expected behavior

I would expect that the colors of strings and function names in a .js file would be different to make the code more human readable.

### Actual behavior

Strings and function names are both green. The syntax group `jsString` is linked to `String` and `jsFuncName` links to `Function`. `String` and `Function` both use `ctermfg=142`. I know that I can override this in my .vimrc, but it should be set for human readability by default.

image

### PR DESCRIPTION
**Pull request by antoineco**
### Description

Custom syntax highlight groups were imported from Gruvbox-Material, and the existing links don't work well with Everforest. I think it will be clear from the included screenshots that the current groups actually _hurt_ the Javascript syntax on Everforest.

I suggest we start from a blank page, and tweak specific groups case by case if needed. The default links look great for most syntax highlight groups already in my opinion (again, see screenshots).

Fixes #70

### Screenshots

Latest version: https://github.com/sainnhe/everforest/pull/82#issuecomment-1217769227

<details>
<summary>
<h4>:art: pangloss/vim-javascript + polyglot</h4>
</summary>

Before

js1-before

After

_Possible improvements: maybe tune `require`, `function` and `this` keywords?_

js1-after

</details>

<details>
<summary>
<h4>:art: built-in Vim syntax</h4>
</summary>

Before

vim1-before

After

_Comment: except for `function` and `undefined` there is literally no difference here._

vim1-after

</details>

<details>
<summary>
<h4>:art: othree/yajs.vim</h4>
</summary>

Before

ya1-before

After

_Possible improvements: maybe adjust main highlight groups so they match the Polyglot version?_

ya1-after

</details>

### CODE REVIEW

**Comment by antoineco** [comment]
@xmready would you mind providing feedback on the screenshots above, especially the Polyglot highlights?

**Comment by sainnhe** [comment]
Directly removing the custom syntax highlighting links will break the design of syntax highlighting logic. Red is used in keywords, orange is used in keywords, yellow is used in types, green is used in functions, aqua is used in strings, purple is used in some special global objects or modules.

I think the problem is that we used too many blue, maybe use less blue will looks better.

**Comment by antoineco** [comment]
But by default most syntaxes accurately link to Vim's base groups (Type, Keyword, Identifier, etc.). For Javascript almost all groups are redefined, doesn't it indicate a problem with the base highlights you mentioned?

I agree that deleting _all_ customisations is extreme, and my ideal outcome would be to adjust this PR until only selected keywords are redefined, and use the defaults as much as possible.
Currently, probably 70% of the highlights imported from gruvbox-material are either redundant (dumb example: `jsType Yellow` is redundant because `Type` is already Yellow) or not matching the conventions from the base groups. As a result, Javascript files look very different from the screenshots from the README.

**Comment by sainnhe** [comment]
I think we can delete the links defined in `pangloss/vim-javascript` and built-in syntax, but IMO yajs is very close to the conversation if we delete blue highlight links.

Maybe we can get start from that.

**Comment by antoineco** [comment]
Yes that's a good suggestion. Keep one, then use it as reference for the other two.

**Comment by antoineco** [comment]
@sainnhe the PR is now in a reviewable shape in my opinion.

I followed your advice:

1. Restored the highlights for `othree/yajs.vim` (all of them)
1. Performed only the minor changes needed to reduce the dominance of blue
1. Used this as a model to edit `pangloss/vim-javascript` and the built-in Vim syntax

In the end I didn't have to perform as many changed as I anticipated. I also looked into the highlight groups which aren't visible in the screenshots (jsBlockLabel, jsDestructuringBlock, ...) to ensure they are still coherent with the Everforest theme. All 3 syntaxes seem to have as good of a parity as possibly achievable.

Let me know what you think.

**Note:** I also want to tackle Treesitter for Javascript, and possibly Typescript as well, but I think that's gonna be easier to review if I address these in separate PRs.

### Screenshots

<details>
<summary>
<h4>pangloss/vim-javascript + polyglot</h4>
</summary>

pang-new1
pang-new2

</details>

<details>
<summary>
<h4>built-in Vim syntax</h4>
</summary>

vim-new1
vim-new2

</details>

<details>
<summary>
<h4>othree/yajs.vim</h4>
</summary>

yajs-new1
yajs-new2

</details>

**Comment by xmready** [comment]
> @xmready would you mind providing feedback on the screenshots above, especially the Polyglot highlights?

With minimal .vimrc and polyglot [my string colors don't match](https://github.com/sainnhe/everforest/issues/70#issuecomment-1215577200) your "before screens", among other things, not sure why.
image



> @sainnhe the PR is now in a reviewable shape in my opinion.

Variable names and such look much better, super great. However your strings are now back to green again unlike your orignal "after" image. The strings being the same color as the function names was kinda the whole purpose of my [original issue](https://github.com/sainnhe/everforest/issues/70#issuecomment-1215577200) #70

**Comment by antoineco** [comment]
@xmready I agree that strings would look much better and create a better feel in Aqua instead of Green because functions are already Green, but @sainnhe mentioned in https://github.com/sainnhe/gruvbox-material/issues/119 that he didn't want to include that change in the Vim syntax (**tl;dr:** apparently it would look good in some places, but bad in others).

For full disclosure, I had this setting applied in my vimrc when I took the initial screenshots, and totally forgot about it (sorry!):

```vim
augroup everforest_theme_overrides
  autocmd!
  " highlight strings differently from functions
  autocmd ColorScheme everforest
  \       hi link jsString Aqua
augroup END
```

The final screenshots were taken with a pristine vimrc.

**Comment by sainnhe** [comment]
> @sainnhe the PR is now in a reviewable shape in my opinion.
> 
> I followed your advice:
> 
> 1. Restored the highlights for `othree/yajs.vim` (all of them)
> 2. Performed only the minor changes needed to reduce the dominance of blue
> 3. Used this as a model to edit `pangloss/vim-javascript` and the built-in Vim syntax
> 
> In the end I didn't have to perform as many changes as I anticipated. I also looked into the highlight groups which aren't visible in the screenshots (jsBlockLabel, jsDestructuringBlock, ...) to ensure they are still coherent with the Everforest theme. All 3 syntaxes seem to have as good of a parity as possibly achievable.
> 
> Let me know what you think.
> 
> **Note:** I also want to tackle Treesitter for Javascript, and possibly Typescript as well, but I think that's gonna be easier to review if I address these in separate PRs.
> 
> ### Screenshots
> #### 🎨 pangloss/vim-javascript + polyglot
> #### 🎨 built-in Vim syntax
> #### 🎨 othree/yajs.vim

pangloss js and built-in syntax looks good, but maybe yajs need further adjustments, too many tokens have lost highlights. Some functions and methods are not highlighted (e.g. `require` and `readFileSync`), is it possible to make it green?

---

> @sainnhe how would you feel about keeping `String -> Green` globally, but override `jString -> Aqua` only for Javascript? Can you think about anything specific that wouldn't work with that color coding?

Yes, if this really have a better overall feeling.

But if functions and methods can't be properly highlighted in yajs, I think it's not a good idea to do so in yajs, because this would make too much aqua (even more than green) which may cause a bad overall feeling.

**Comment by antoineco** [comment]
I noticed that issue with othree/yajs.vim indeed.

The problem with this syntax is that it makes no distinction whatsoever between identifiers, attributes and functions. It categorises a lot of different things as either `javascriptBlock` (after a period `.`) or `javascriptIdentifierName` (everything else), so if you link this group to a warm color, suddenly your entire source file [turns into that color](https://user-images.githubusercontent.com/3299086/184884769-e75f2c39-8048-4695-9f60-893e71022c50.png) (which is [blue](https://github.com/sainnhe/everforest/blob/4ac36ab7b4db3f4788128971882ef897fa567652/colors/everforest.vim#L1686) in the current Everforest revision):

```javascript
const fs = require('fs');
//    │    └─ javascriptIdentifierName
//    └─ javascriptIdentifierName
```

```javascript
handleExportedDeclaration(statement, flags);
// │                      │          └─ javascriptIdentifierName
// │                      └─ javascriptIdentifierName
// └─ javascriptIdentifierName
```

```javascript
let contents = fs.readFileSync(fileName, 'utf8');
//  │          │  └─ javascriptBlock
//  │          └─ javascriptIdentifierName
//  └─ javascriptIdentifierName
```

The only functions that are recognized as functions are _built-in functions_ ([example](https://github.com/othree/yajs.vim/blob/2bebc45ce94d02875803c67033b2d294a5375064/syntax/yajs/es6-set.vim#L6), see also other files in this directory):

```javascript
sourceFile.statements.forEach((statement) => {}
// │       │          └─ javascriptES6SetMethod
// │       └─ javascriptBlock
// └─ javascriptIdentifierName
```

My opinion on this is that syntax highlights are harder to tell apart when a warm color dominates (e.g. blue) over the foreground color, and in that regard I think othree/yajs.vim is poorly designed. Which is probably why othree/yajs.vim doesn't link `javascriptIdentifierName` and `javascriptBlock` to anything by default in the first place.

**Comment by sainnhe** [comment]
OK, let's change it to aqua. Do we need any further adjustments? If not, go ahead and merge it ;)

**Comment by antoineco** [comment]
Here are samples of pangloss/vim-javascript with `jsString -> Aqua` applied in commit fc7dacf93e1cfca419412296660d4209733c3c99.

<details>
<summary>
<h4>:art: pangloss/vim-javascript</h4>
</summary>

jsstring-aqua1
jsstring-aqua2

</details>

See https://github.com/sainnhe/everforest/pull/82#issuecomment-1217769227 for a comparison with `jsString -> Green`.

**Comment by xmready** [comment]
Just now realized that JS backtick strings are still green, but double and single quoted stings are aqua as intended.

**Comment by antoineco** [comment]
@xmready TIL that Javascript has backtick quotes 😅  Thanks for reports.

**Comment by xmready** [comment]
> @xmready TIL that Javascript has backtick quotes sweat_smile Thanks for reporting.

Haha, yea they are used for evaluating expressions and functions inside of the the string, and also for multi-line string blocks. Thank you both for being so responsive!

**Pull request merged**
